"""Built-in LLM provider presets."""

PRESET_PROVIDERS = [
    {
        "provider_key": "deepseek",
        "provider_name": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "api_format": "openai",
        "model_name": "deepseek-v4-flash",
        "icon": "deepseek",
        "description": "DeepSeek 官方 OpenAI 兼容接口",
        "models": ["deepseek-v4-flash", "deepseek-v4-pro", "deepseek-chat", "deepseek-reasoner"],
    },
    {
        "provider_key": "qwen",
        "provider_name": "通义千问",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "api_format": "openai",
        "model_name": "qwen-plus",
        "icon": "qwen",
        "description": "阿里云百炼 DashScope OpenAI 兼容接口",
        "models": ["qwen-plus", "qwen-turbo", "qwen-max", "qwen-long"],
    },
    {
        "provider_key": "doubao",
        "provider_name": "豆包",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "api_format": "openai",
        "model_name": "doubao-seed-1-6-250615",
        "icon": "doubao",
        "description": "火山方舟豆包 OpenAI 兼容接口",
        "models": [
            "doubao-seed-1-6-250615",
            "doubao-seed-1-6-thinking-250615",
            "doubao-1-5-pro-32k-250615",
        ],
    },
    {
        "provider_key": "xiaomi",
        "provider_name": "小米 MiMo",
        "base_url": "https://api.xiaomimimo.com/v1",
        "api_format": "openai",
        "model_name": "mimo-v2.5-pro",
        "icon": "xiaomi",
        "description": "小米 MiMo OpenAI 兼容接口",
        "models": ["mimo-v2.5-pro"],
    },
    {
        "provider_key": "ollama",
        "provider_name": "本地 Ollama",
        "base_url": "http://127.0.0.1:11434",
        "api_format": "ollama",
        "model_name": "llama3.1",
        "icon": "ollama",
        "description": "连接服务器可访问的 Ollama 本地大模型服务，默认不需要 API Key",
        "models": ["llama3.1", "qwen2.5", "qwen2.5-coder", "deepseek-r1", "mistral", "gemma2"],
        "requires_api_key": False,
        "base_url_editable": True,
    },
]
